name: bicep build and deploy

on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  bicep-build-and-deploy:
    # Name the Job
    name: bicep build and deploy
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Install bicep CLI
      - name: Install bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
          bicep --help
           
      # Transpile bicep file into ARM template
      - name: Build ARM Template from bicep file
        run: |
          bicep build ./main.bicep
          
      # Transpile bicep file into ARM template
      # - name: Build ARM Template from bicep file
      #   uses: aliencube/bicep-build-actions@v0.1 # pulls latest release from bicep repo
      #   with:
      #     files: './main.bicep'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Emit template what-if
      - name: Run what-if
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account show
            az deployment sub what-if -f ./main.json -l eastus

      # Deploy template
      - name: Deploy template
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # az account show
            # az deployment sub create -f ./main.json -l eastus